repos:
    # Sort order of Python imports
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
    # Remove unused Python imports
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.2.0
      hooks:
        - id: autoflake
          args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports"]

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: check-yaml
