name: Automated tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - name: linux py39-mindeps
            os: ubuntu-20.04
            python-version: '3.9'
            pip-extras: '"sunpy<4.1" "astropy<5.1" "matplotlib<3.5"'

          - name: linux py311-devdeps
            os: ubuntu-20.04
            python-version: '3.11'
            pip-extras: git+https://github.com/astropy/astropy git+https://github.com/sunpy/sunpy git+https://github.com/dstansby/streamtracer

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test] ${{ matrix.pip-extras }}
    - name: Run tests
      run: |
        pytest --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
